version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
    expose:
      - "3001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - app
    ports:
      - "80:80"  # HTTP порт, можно заменить на 443 при наличии SSL
    restart: always

volumes:
  postgres-data:
