version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 2110
      POSTGRES_DB: eamj
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user:2110@db:5432/eamj"
      JWT_SECRET: "your_secret"
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://backend:3001"
    depends_on:
      - backend

volumes:
  pgdata: